export const USER_PRE_BOOKING_DATA = "USER_PRE_BOOKING_DATA";
export const USER_ORDER_DATA = "USER_ORDER_DATA";
export const USER_PURCHASE_BUTTON_SHOW = "USER_PURCHASE_BUTTON_SHOW";
export const USER_PURCHASE_NO_ORDERS = "USER_PURCHASE_NO_ORDERS";
